### ISSUE TITLE
报错 ERROR ConsoleLog - 连接到mcl失败:

### ISSUE THREAD

**Issue by bingaha** [GardenHamster/Theresa3rd-Bot#1]
您好，我在使用bot的过程中，配置在配置文件appsettings.Production.json中配置了mcl-http的ip，
```json
{
  "Mirai": {
    "host": "127.0.0.1",
    "port": "9800",
    "authKey": "INITKEYKwj3SqLu",
    "botQQ": "2889126065"
  },
  "Database": {
    "ConnectionString": "Data Source=127.0.0.1;port=3306;Initial Catalog=theresa_bot;uid=root;pwd=123456;"
  }
}
```
并且mcl和httpapi插件是运行成功了的，我用telnet测试9800端口是开启状态的
![Snipaste_2022-03-16_20-11-04](https://user-images.githubusercontent.com/37445781/158587210-d4685b4b-877a-4ff5-bc31-cba5f26edaa8.png)
但是连接会报以下错误，请问是我哪里没有配置正确吗
![Snipaste_2022-03-16_20-12-15](https://user-images.githubusercontent.com/37445781/158587364-1763b8f9-d2e6-453d-8d85-5b72ee1f3a71.png)

**Comment by GardenHamster** [comment]
404了，可能mcl配置没改好，检查一下config\net.mamoe.mirai-api-http\setting.yml这个文件
