### ISSUE TITLE
在ubuntu下无法运行

### ISSUE THREAD

**Issue by willyautoman** [GardenHamster/Theresa3rd-Bot#12]
系统： ubuntu 22.04
服务器配置 ：腾讯云服务器 4H4G8M
已按照文档进行相关配置，后按照命令运行，仅出现两行文字
![image](https://user-images.githubusercontent.com/47789371/200160658-f59105f3-cc92-4334-aede-7a458f52529a.png)

**Comment by GardenHamster** [comment]
log目录下有日志吗

**Comment by willyautoman** [comment]
有两个日志，如下：
![image](https://user-images.githubusercontent.com/47789371/200166220-601c99a5-a9c5-487b-b74f-e5c8448cae8a.png)

第一个日志是以日期命名的
![image](https://user-images.githubusercontent.com/47789371/200166161-8dc560e0-fabf-4914-9aac-8a5bbb0056ff.png)
但是这个日志是我第一次运行时忘记配数据库出现的，后期已经重新配置。
第二个日志（log-info.log）,并没有显示相关错误
![image](https://user-images.githubusercontent.com/47789371/200166208-cc743ee8-d3b7-4787-bbec-ecdbaa9270fc.png)

**Comment by willyautoman** [comment]
按教程中操作，仅
![image](https://user-images.githubusercontent.com/47789371/200166277-ab303edb-e4c6-4093-8454-7739857c2e1c.png)
无法运行（原因是epel是centos系的命令），其他操作均已执行完毕

**Comment by GardenHamster** [comment]
先检查一下数据库能不能连上吧

**Comment by willyautoman** [comment]
嗯。。。。发现问题了，是这样，当我第一次连接失败后，整个程序似乎都会定格在那一个状态，我最后尝试将项目删除并重新解压后，程序课正常运行，采问题请后续予以解决

**Comment by willyautoman** [comment]
嗯。。。。发现问题了，是这样，当我第一次连接失败后，整个程序似乎都会定格在那一个状态，我最后尝试将项目删除并重新解压后，程序就可以正常运行，此问题请后续予以解决

**Comment by GardenHamster** [comment]
程序能正常运行吗，目前epel只有在合成gif图时会用到

**Comment by willyautoman** [comment]
好像不太行，虽然已显示正常启动，但是无法接收消息。
![image](https://user-images.githubusercontent.com/47789371/200180971-188d24e9-3ac9-40df-bd1f-c65514fc13d9.png)
![image](https://user-images.githubusercontent.com/47789371/200181062-98eea6aa-f0fb-465c-b5c1-f9af77cb0e4e.png)

**Comment by GardenHamster** [comment]
配置文件里的可用群设置好了吗，群号有没有填错

**Comment by GardenHamster** [comment]
v0.8.0移除了libgdiplus的引用，可以更新一下
