### ISSUE TITLE
启动之后在私聊机器人时出现奇怪日志问题

### ISSUE THREAD

**Issue by Mepuru** [GardenHamster/Theresa3rd-Bot#15]
错误产生原因：在私聊时快速发送消息后，Bot在Mirai控制台会一直重复刷消息

反馈错误为：
FriendMessageEvent异常
未知的服务器返回。
详细请查看Log日志

Mirai协议:Macos
Mirai核心版本:2.13.2

另外可否单独设置一个自动回复颜文字的开关
我使用多个框架并不需要私聊自动回复颜文字
![7$QR5%00IU P$JSJMT)%@NR](https://user-images.githubusercontent.com/64205945/209126884-6f67c315-4ca7-428a-9eae-baa3dd20e35c.png)

**Comment by GardenHamster** [comment]
以前加这个颜文字只是为了方便萌新测试bot能不能正常收发消息的，以后我把它去掉好了

**Comment by GardenHamster** [comment]
v0.8.0把颜文字移除了，可以更新一下
