### ISSUE TITLE
无法连接mirai-http-api

### ISSUE THREAD

**Issue by 1233Ao** [GardenHamster/Theresa3rd-Bot#16]
提示2022-12-29 20:24:08,208 [4] ERROR ConsoleLog - 指定的文件不存在。
[log-info.log](https://github.com/GardenHamster/Theresa3rd-Bot/files/10319448/log-info.log)
[20221229.log](https://github.com/GardenHamster/Theresa3rd-Bot/files/10319449/20221229.log)

**Comment by lingyuins** [comment]
将mirai-http-api中单个账号模式关闭
并将认证模式打开
