### ISSUE TITLE
欢迎 dalao 入驻 KnifeHub 平台！

### ISSUE THREAD

**Issue by yiyungent** [GardenHamster/Theresa3rd-Bot#18]
> 如果有打扰的话，再次非常抱歉，关闭本 issue 即可，谢谢！

dalao 好棒的项目！

不考虑入驻一下 [KnifeHub](https://github.com/yiyungent/KnifeHub) 吗? (将本项目贡献为插件) (逃(#^.^#)

**Comment by GardenHamster** [comment]
emmm，我是个上班族，写这个插件只是为了自娱自乐，实在没多余精力为平台做贡献，抱歉了
