### ISSUE TITLE
一直卡在最后一步连接超时

### ISSUE THREAD

**Issue by xywdyw** [GardenHamster/Theresa3rd-Bot#19]
请问一下这个是什么原因怎么解决？同时也启动了mcl
![-49ab4495acbf89eb](https://user-images.githubusercontent.com/123064959/214103784-518254ab-ae16-433d-a97e-d75509cc6454.jpg)
![45a081d8256a8ce7](https://user-images.githubusercontent.com/123064959/214103801-9fe53062-6ce8-442c-b6dd-5e07f09e0a94.jpg)

**Comment by GardenHamster** [comment]
mirai http api的配置没配好，你参考官方文档里面的改一改
[https://github.com/project-mirai/mirai-api-http#settingyml模板](https://github.com/project-mirai/mirai-api-http#settingyml%E6%A8%A1%E6%9D%BF)

**Comment by xywdyw** [comment]
> mirai http api的配置没配好，你参考官方文档里面的改一改 [https://github.com/project-mirai/mirai-api-http#settingyml模板](https://github.com/project-mirai/mirai-api-http#settingyml%E6%A8%A1%E6%9D%BF)

谢谢，已经解决了
