### ISSUE TITLE
bot配置文件在哪？？？？

### ISSUE THREAD

**Issue by HD12138** [GardenHamster/Theresa3rd-Bot#24]
项目都在centos7上部署，到时候就是bot配置还有几个json文件没有，加证书No packages marked for update

**Comment by HD12138** [comment]
[root@Learn iTXTech]# ./mcl --update-package net.mamoe:mirai-api-http --channel stable-v2 --type plugin
  21:32:26 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  21:32:26 [INFO] Runtime: OpenJDK 64-Bit Server VM 17.0.6 (arch: 64)
  21:32:26 [INFO] https://github.com/iTXTech/mirai-console-loader
  21:32:26 [INFO] This program is licensed under GNU AGPL v3
  21:32:26 [INFO] Package "net.mamoe:mirai-api-http" has been updated.

**Comment by HD12138** [comment]
appsettings.Production.json 文件找不到

**Comment by HD12138** [comment]
[root@Learn Theresa3rd-Bot]# nohup dotnet TheresaBot.MiraiHttpApi.dll --launch-profile Production --urls http://0.0.0.0:8088
nohup: 忽略输入并把输出追加到"nohup.out"
已放弃

**Comment by HD12138** [comment]
![图片](https://user-images.githubusercontent.com/95847253/221087073-9bc47081-b2ab-4cee-9937-d5e1b182d51e.png)
centos7没反应

**Comment by GardenHamster** [comment]
提供一下相关的错误日志，不然我不知道问题出现在哪
