### ISSUE TITLE
setu指令都未授权（Instructions are not authorized）

### ISSUE THREAD

**Issue by ruotianyu** [GardenHamster/Theresa3rd-Bot#26]
yml里的设置全部已经改好了，但是还是显示未授权（yaml All the settings have been changed, but it still shows Unauthorized）

**Comment by GardenHamster** [comment]
麻烦详细的报错发一下

**Comment by ruotianyu** [comment]
> 麻烦详细的报错发一下

没有报错，就是单纯的，qq群里发setu什么的，就是显示未授权

**Comment by GardenHamster** [comment]
这个插件并没有什么需要授权的地方，你在Log目录下找一下日志帖出来看看，还有聊天记录也截个图

**Comment by ruotianyu** [comment]
> 这个插件并没有什么需要授权的地方，你在Log目录下找一下日志帖出来看看，还有聊天记录也截个图

ok

**Comment by ruotianyu** [comment]
> 这个插件并没有什么需要授权的地方，你在Log目录下找一下日志帖出来看看，还有聊天记录也截个图

解决了，删除日志重新加载就行了，谢大佬提醒log
