### ISSUE TITLE
【功能请求】可选开启@bot时的指令提示

### ISSUE THREAD

**Issue by KaRuiqin** [GardenHamster/Theresa3rd-Bot#27]
这和其他插件会产生冲突，故希望增加一个指令提示的开关。
![1678530387556](https://user-images.githubusercontent.com/69111766/224479291-f66f3409-f63f-4b2c-b24c-f8b237d29c12.png)

**Comment by GardenHamster** [comment]
不是很理解你说的具体需求，如果不想让bot提示指令的话，你可以改一下配置这里
https://github.com/GardenHamster/Theresa3rd-Bot/blob/102275ae27f5aa15c439e6b6c23d2a22c3aa3140/Theresa3rd-Bot/TheresaBot.Main/botsettings.yml#L14

**Comment by KaRuiqin** [comment]
> 不是很理解你说的具体需求，如果不想让bot提示指令的话，你可以改一下配置这里
> 
> https://github.com/GardenHamster/Theresa3rd-Bot/blob/102275ae27f5aa15c439e6b6c23d2a22c3aa3140/Theresa3rd-Bot/TheresaBot.Main/botsettings.yml#L14

之前配置文件翻了半天没找到，原来就在这里（
我的问题已解决，感谢大佬的回复 >_<
