### ISSUE TITLE
日榜一览图合成失败

### ISSUE THREAD

**Issue by yuyang0702** [GardenHamster/Theresa3rd-Bot#29]
日榜一览图合成失败
The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory

**Comment by yuyang0702** [comment]
您好，我这边是合集类都都没办法正常生成图片，我看服务器上图片已经下载下来了，但是没有发正常加载，单个图片的话可以正常在qq上面显示。

**Comment by GardenHamster** [comment]
完整的报错发一下，Log目录下面有

**Comment by yuyang0702** [comment]
2023-03-21 14:05:52,960 [22] ERROR RollingLog [(null)] - 日榜一览图合成失败
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at TheresaBot.Main.Helper.PixivRankingDrawHelper.DrawPreview(PixivRankingInfo rankingInfo, List`1 datas, String savePath)
   at TheresaBot.Main.Handler.PixivRankingHandler.createPreviewImg(PixivRankingInfo rankingInfo, List`1 datas, String savePath)

**Comment by GardenHamster** [comment]
你用的插件版本是多少？还有用的是Window还是Linux？

**Comment by yuyang0702** [comment]
> 你用的插件版本是多少？还有用的是Window还是Linux？

用的LINUX，插件版本是2.9.1

**Comment by GardenHamster** [comment]
检查下配置文件`botsettings.yml`上的windows路径都改成Linux路径没

**Comment by yuyang0702** [comment]
> 检查下配置文件`botsettings.yml`上的windows路径都改成Linux路径没

改了，已经可以确认图片在这个路径上下载下来了，但是就是没有体现在qq的聊天窗口里面。

**Comment by GardenHamster** [comment]
那你看看`BotDownload\PixivPreview`路径下有生成这样的大图没

![image](https://user-images.githubusercontent.com/89188316/226550640-c80c394c-b280-48c5-a76e-9b5f6d2bcc44.png)

还有就是我不清楚你说的`没有体现`和`没有发正常加载`是什么情况

可以的话发一下相关聊天记录截图

**Comment by yuyang0702** [comment]
> 那你看看`BotDownload\PixivPreview`路径下有生成这样的大图没
> 
> ![image](https://user-images.githubusercontent.com/89188316/226550640-c80c394c-b280-48c5-a76e-9b5f6d2bcc44.png)
> 
> 还有就是我不清楚你说的`没有体现`和`没有发正常加载`是什么情况
> 
> 可以的话发一下相关聊天记录截图

linux路径下BotDownload\PixivPreview没有生成大图，但是BotDownload/PixivWork/生成了很多单独的图片。
![微信截图_20230321163147](https://user-images.githubusercontent.com/48078283/226553630-ae062f70-9c57-495d-a6df-a685f5a844c6.png)
![微信截图_20230321163204](https://user-images.githubusercontent.com/48078283/226553643-33aa290e-fbf1-4f5f-8958-a074a8968c9e.png)
qq发送日榜后提示如下图:
![微信图片_20230321163024](https://user-images.githubusercontent.com/48078283/226553723-8d2c3117-ca1d-4840-b0c2-e1fa3e17988a.jpg)
![微信图片_20230321163036](https://user-images.githubusercontent.com/48078283/226553739-20edff80-0dc0-42c5-9840-ddf74e9a12f4.jpg)

**Comment by GardenHamster** [comment]
Pixiv和General的配置发一下，晚上我再测试一下

**Comment by yuyang0702** [comment]
> Pixiv和General的配置发一下，晚上我再测试一下

下面是我botsettings的配置:
General:                                                                            #基础设置
    Prefix:                     '#'                                                 #指令前缀
    DownloadPath:               'BotImg/download'                                #下载文件的存放目录
    DownPathCleanCron:          '0 0 4 * * ?'                                       #下载目录清理定时器，Cron表达式，空值表示不清理，格式：0 0 4 * * ?
    DownErrorImgPath:           'BotImg/face/downError.png'                      #图片下载失败时的替代图片
    ErrorGroups:                [940931362]                                         #错误日志群，发生错误时会将日志发送到这些群
    ErrorMsg:                   |                                                   #处理异常时返回的消息
                                出了点小问题，稍后再试吧
                                [image:BotImg/face/emmm.jpg]
    DisableMsg:                 '该功能未开启'                                      #功能未启用时返回的消息
    NoPermissionsMsg:           '该功能未授权'                                      #功能未授权时返回的消息
    ManagersRequiredMsg:        '该功能需要管理员执行'                              #需要管理员权限时返回的消息
    SetuCustomDisableMsg:       '自定义功能已关闭'                                  #禁用自定义时返回的消息
    SendRelevantCommands:       true                                                #接收到的指令不存在时，提示类似的可执行指令

Pixiv:
    FreeProxy:                  false                                               #开启pixiv免代理模式，启用后将使用{ImgProxy}下载图片
    HttpProxy:                  ''                                                  #pixiv代理地址，值为空表示直连，FreeProxy启用后失效，格式：http://127.0.0.1:7890
    ImgProxy:                   ''                                                  #图片代理地址，值为空表示不使用代理，FreeProxy启用后使用该值下载图片，默认：https://i.pixiv.re
    ImgShowMaximum:             1                                                   #同一个作品最多显示N张图片，0表示无限制
    TagShowMaximum:             5                                                   #同一个作品最多显示N个标签，0表示无限制
    UrlShowMaximum:             3                                                   #同一个作品最多显示N条原图链接，0表示无限制
    ImgSize:                    'thumb'                                             #发送色图的尺寸：thumb，small，regular，original。默认为thumb
    ImgResend:                  1                                                   #涩图发送失败后：0:不重发，1:不带图片重发，2:旋转180°后重发，3:模糊处理后重发
    R18ImgBlur:                 5                                                  #R18图片高斯模糊处理程度，范围：5~100
    OriginUrlProxy:             'https://pixiv.ilove.ski'                           #pixiv原图链接的代理地址，默认：https://i.pixiv.re(有频率限制)
    SendImgBehind:              false                                               #将涩图信息和图片分开发送，先发送作品信息，后发送图片，可以开启此项避免消息被吞
    ImgRetryTimes:              2                                                   #图片下载失败后重试次数，0表示不重试
    ErrRetryTimes:              2                                                   #读取作品失败后的重试次数，0表示不重试
    CookieExpire:               5184000                                             #cookie失效时间(秒)，超过该时间后需要使用命令更新cookie，建议cookie每60天更新一次
    CookieExpireMsg:            'emmmm,cookie过期了,请艾特管理员更新cookie'         #cookie过期时返回的消息
    Template:                   |                                                   #pixiv模版，值为空时将使用默认模版
                                PixivId：{PixivId}，标题：{IllustTitle}，画师：{UserName}，画师id：{UserId}，
                                收藏：{BookmarkCount}，赞：{LikeCount}，浏览：{ViewCount}，
                                标签图片：{RelevantCount}张，作品图片:{PageCount}张
                                标签：{Tags}，点击下方链接可以查看原图
                                {Urls}
    GeneralTarget:              1.0                                                 #普通作品指标，比如：一张合格的涩图的最低收藏率需要达到(MinBookmark*GeneralTarget)，MinBookPerHour和MinBookRate同理
    AITarget:                   0.5                                                 #AI作品指标(同上)
    R18Target:                  1.2                                                 #R18作品指标(同上)

**Comment by GardenHamster** [comment]
Linux上是缺了个依赖，过两天我发布个新包出来更新一下就行

**Comment by yuyang0702** [comment]
> Linux上是缺了个依赖，过两天我发布个新包出来更新一下就行

好的，麻烦了，谢谢

**Comment by GardenHamster** [comment]
在[v0.8.3](https://github.com/GardenHamster/Theresa3rd-Bot/releases/tag/v0.8.3)中修复了
