### ISSUE TITLE
win11上运行mcl.cmd没有反应

### ISSUE THREAD

**Issue by shi-g-c** [GardenHamster/Theresa3rd-Bot#3]
win11上运行mcl.cmd没有反应；然后跳过这个去执行命令时提示“ARY”不是外部命令”。还有“-jar”也不是外部命令

**Comment by GardenHamster** [comment]
这....，win11还没优化到位，出这种奇奇怪怪的问题也挺正常...

**Comment by GardenHamster** [comment]
可以先自己排查一下jdk环境有没有安装好，实在不行可以到https://github.com/iTXTech/mirai-console-loader/issues下面给作者发issues

**Comment by shi-g-c** [comment]
呜呜呜，好难弄，放弃了。等过两年计算机技术高深一点后再来弄。给你点个star。
