### ISSUE TITLE
mcl正常运行 插件找不到机器人

### ISSUE THREAD

**Issue by a15276317656** [GardenHamster/Theresa3rd-Bot#30]
![image](https://user-images.githubusercontent.com/119063905/226975285-96db7ebf-645a-4e4a-82b2-129be4cb5fd9.png)
![image](https://user-images.githubusercontent.com/119063905/226975485-e25c7cfd-5c71-42ad-870f-753bc00e993a.png)
![image](https://user-images.githubusercontent.com/119063905/226975729-8708adde-b961-44b9-8e51-155aa73dbaab.png)
![image](https://user-images.githubusercontent.com/119063905/226975832-e325532b-d575-400f-b26e-2c5b377e30ca.png)

**Comment by GardenHamster** [comment]
检查一下mirai-http-api配置好没

**Comment by a15276317656** [comment]
![image](https://user-images.githubusercontent.com/119063905/227117333-7eff6728-73cc-45bd-98ea-e9093ebdc244.png)

**Comment by a15276317656** [comment]
之前可以用，没动过配置

**Comment by GardenHamster** [comment]
应该有什么地方没配置好，你再检查一下吧，实在不行就重启或者重新安装试试
