### ISSUE TITLE
R18系列出错

### ISSUE THREAD

**Issue by yuyang0702** [GardenHamster/Theresa3rd-Bot#31]
2023-03-24 17:59:29,758 [41] ERROR RollingLog [(null)] - replyRankingInfo异常
TheresaBot.Main.Exceptions.PixivException: 获取排行信息失败
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TheresaBot.Main.Helper.PixivHelper.GetPixivRankingAsync[T](String url, String operation, Dictionary`2 headerDic, Int32 retryTimes, Int32 timeout)
   --- End of inner exception stack trace ---
   at TheresaBot.Main.Helper.PixivHelper.GetPixivRankingAsync[T](String url, String operation, Dictionary`2 headerDic, Int32 retryTimes, Int32 timeout)
   at TheresaBot.Main.Helper.PixivHelper.GetPixivRankingData(String mode, Int32 page, String date)
   at TheresaBot.Main.Business.PixivRankingBusiness.getRankingDatas(PixivRankingMode rankingMode, String search_date)
   at TheresaBot.Main.Business.PixivRankingBusiness.getRankingInfo(PixivRankingItem rankingItem, PixivRankingMode rankingMode, String search_date, Int32 retryTimes)
   at TheresaBot.Main.Business.PixivRankingBusiness.getRankingInfo(PixivRankingItem rankingItem, PixivRankingMode rankingMode, String search_date, Int32 retryTimes)
   at TheresaBot.Main.Handler.PixivRankingHandler.replyRankingInfo(GroupCommand command, PixivRankingMode rankingMode, PixivRankingItem rankingItem)

**Comment by GardenHamster** [comment]
是哪个日榜，哪天的日榜

**Comment by yuyang0702** [comment]
> 日榜的配置发一下看看

PixivRanking:                                                                       #Pixiv日榜/周榜/月榜/AI榜/男性向日榜功能
    Enable:                     true                                                #是否启用
    ProcessingMsg:              '正在获取榜单信息，需要亿点时间...'                 #开始执行前返回的消息
    Template:                   '{Date}{Ranking}精选，数据缓存{CacheSeconds}秒'     #消息模版
    MaxScan:                    300                                                 #每个排行榜最多扫描前N个作品
    PreviewInPage:              30                                                  #合成一览图中，每张一览图最多显示多少个作品
    SortType:                   2                                                   #排序方式，0榜单排名，1收藏数排序，2收藏率排序，3点赞数排序，4点赞率排序
    GroupCD:                    300                                                 #共享CD(秒)，使用命令后全群需要CD才能重新使用该功能
    CacheSeconds:               3600                                                #每个榜单数据缓存时间
    SendDetail:                 0                                                   #同时发送前N个作品的图片和详情
    Daily:                                                                          #日榜
        Enable:                 true                                                #是否启用
        Commands:               ['日榜']                                            #命令
        R18Commands:            ['R18日榜']                                         #R18命令
        MinRatingCount:         300                                                 #榜单信息中的最低点赞数，用于对作品进行初步过滤
        MinRatingRate:          0.1                                                 #榜单信息中的最低点赞率，用于对作品进行初步过滤
        MinBookCount:           500                                                 #作品最低实时收藏数，用于对作品进一步过滤
        MinBookRate:            0.1                                                 #作品最低实时收藏率，用于对作品进一步过滤
    DailyAI:                                                                        #AI日榜
        Enable:                 true                                                #是否启用
        Commands:               ['ai榜','ai日榜']                                   #命令
        R18Commands:            ['R18AI榜','R18AI日榜']                             #R18命令
        MinRatingCount:         300                                                 #榜单信息中的最低点赞数，用于对作品进行初步过滤
        MinRatingRate:          0.1                                                 #榜单信息中的最低点赞率，用于对作品进行初步过滤
        MinBookCount:           500                                                 #作品最低实时收藏数，用于对作品进一步过滤
        MinBookRate:            0.1                                                 #作品最低实时收藏率，用于对作品进一步过滤
    Male:                                                                           #男性向(受男性欢迎)日榜
        Enable:                 true                                                #是否启用
        Commands:               ['LSP日榜']                                         #命令
        R18Commands:            ['R18LSP日榜']                                      #命令
        MinRatingCount:         300                                                 #榜单信息中的最低点赞数，用于对作品进行初步过滤
        MinRatingRate:          0.18                                                #榜单信息中的最低点赞率，用于对作品进行初步过滤
        MinBookCount:           500                                                 #作品最低实时收藏数，用于对作品进一步过滤
        MinBookRate:            0.24                                                #作品最低实时收藏率，用于对作品进一步过滤
    Weekly:                                                                         #周榜
        Enable:                 true                                                #是否启用
        Commands:               ['周榜']                                            #命令
        R18Commands:            ['R18周榜']                                         #R18命令
        MinRatingCount:         1000                                                #榜单信息中的最低点赞数，用于对作品进行初步过滤
        MinRatingRate:          0.18                                                #榜单信息中的最低点赞率，用于对作品进行初步过滤
        MinBookCount:           1500                                                #作品最低实时收藏数，用于对作品进一步过滤
        MinBookRate:            0.25                                                #作品最低实时收藏率，用于对作品进一步过滤
    Monthly:                                                                        #月榜
        Enable:                 true                                                #是否启用
        Commands:               ['月榜']                                            #命令
        MinRatingCount:         100                                                 #榜单信息中的最低点赞数，用于对作品进行初步过滤
        MinRatingRate:          0.01                                                #榜单信息中的最低点赞率，用于对作品进行初步过滤
        MinBookCount:           3000                                                #作品最低实时收藏数，用于对作品进一步过滤
        MinBookRate:            0.155                                               #作品最低实时收藏率，用于对作品进一步过滤
    Subscribes:                                                                     #定时推送
        - Enable:               false                                               #是否启用
          Cron:                 '0 30 10 * * ?'                                     #cron表达式(需要自行百度cron格式)
          Groups:               [940931362]                                         #推送到群
          Contents:             ['Daily','DailyAI']                                 #推送内容，可选Daily/DailyAI/Male/Weekly/Monthly/DailyR18/DailyAIR18/MaleR18/WeeklyR18
          SendDetail:           10                                                  #同时发送前N个作品的图片和详情

        - Enable:               false                                               #是否启用
          Cron:                 '0 40 10 ? * SUN'                                   #cron表达式(需要自行百度cron格式)
          Groups:               [940931362]                                         #推送到群
          Contents:             ['Weekly','Monthly']                                #推送内容，可选Daily/DailyAI/Male/Weekly/Monthly/DailyR18/DailyAIR18/MaleR18/WeeklyR18
          SendDetail:           10                                                  #同时发送前N个作品的图片和详情

**Comment by GardenHamster** [comment]
指定日期获取的日榜会有同样问题吗，如果只是某一天的r18日榜有问题的话就先不处理了

**Comment by yuyang0702** [comment]
> 指定日期获取的日榜会有同样问题吗，如果只是某一天的r18日榜有问题的话就先不处理了

不是日榜，是只要涉及到R18关键字的所有功能都会提示这个错误

**Comment by GardenHamster** [comment]
刚又调试了一下，没复现出类似问题。盲猜是你pixiv账号没把R18打开

**Comment by GardenHamster** [comment]
![image](https://user-images.githubusercontent.com/89188316/227708698-dcb4f591-526e-4836-b245-b26e6498124a.png)

**Comment by GardenHamster** [comment]
你在账号设置里面开一下R18，退出登录，清理缓存，然后再重新设置一下cookie试试

**Comment by yuyang0702** [comment]
> 刚又调试了一下，没复现出类似问题。盲猜是你pixiv账号没把R18打开

...确实是这个问题，谢谢了，感恩！
