### ISSUE TITLE
【功能请求】关于一些对功能的请求

### ISSUE THREAD

**Issue by bf179** [GardenHamster/Theresa3rd-Bot#32]
⒈请问大佬会考虑添加发送多张涩图的功能吗，比如#涩图 tag count这样
  ⒉关于添加好友和进群，是否可以通过在qq发送指令完成
  3.对一些配置项的修改，是否也可以通过qq私聊发送指令完成，比如白名单黑名单，高斯模糊的配置等等
  4.只是提一下，有没有考虑会添加本子搜索的功能，/主要是关于哔咔

**Comment by bf179** [comment]
5.还有一点就是关于白名单标签，优先级高于被屏蔽的标签那种(当一张图包含被屏蔽的标签的时候不应该展示，但是当其包含白名单标签除外)
6.命令的关键字默认是英文的# 不知道是否能修改为中文＃和英文#都能生效

**Comment by GardenHamster** [comment]
关于第1点：
- 因为没有找到Pixiv哪个接口可以一次性返回多个作品的收藏数和浏览数，所以只能逐个作品去请求，然后通过这类数据去过滤出比较靠谱的作品。
- 由于想要尽量减少请求pixiv的次数，所以就只返回了第一张符合预期的涩图
- 使用其他涩图api倒是可以做到，以后会考虑加入

关于第2点：
- 应该有其他插件可以实现类似的功能的，个人认为没必要把它加进来，而且用pad协议登录bot的同时还可以用手机登录同一个账号不是吗

**Comment by GardenHamster** [comment]
关于第4点：
- 不会做类似的功能了，建议在Mirai社区寻找类似的插件

关于第5点：
- 可以有，但是适用的场景并不多

关于第6点：
- 晚点将指令前缀修改为可配置多个

关于第7点：
- 行不通，TX有风控机制，只要其中一张图发不出来，那么整个聊天记录都发不出来，而且mirai发送聊天记录还有图片数量限制

关于第8点：
- 另外两个api在不指定标签的情况下其实就已经是随机返回涩图了
- 而且涩图api收录同一个标签的涩图数量并不多，有可能你请求的标签只有那么一两张涩图
- 所以这样做的意义不大

**Comment by bf179** [comment]
> 关于第4点：
> 
> * 不会做类似的功能了，建议在Mirai社区寻找类似的插件
> 
> 关于第5点：
> 
> * 可以有，但是适用的场景并不多
> 
> 关于第6点：
> 
> * 晚点将指令前缀修改为可配置多个
> 
> 关于第7点：
> 
> * 行不通，TX有风控机制，只要其中一张图发不出来，那么整个聊天记录都发不出来，而且mirai发送聊天记录还有图片数量限制
> 
> 关于第8点：
> 
> * 另外两个api在不指定标签的情况下其实就已经是随机返回涩图了
> * 而且涩图api收录同一个标签的涩图数量并不多，有可能你请求的标签只有那么一两张涩图
> * 所以这样做的意义不大

对于第八点，其实我是希望在不指定标签时返回的全都是萝莉标签的图(•̀⌄•́)

**Comment by bf179** [comment]
辛苦大佬了，第七点其实是我觉得或许可以定期推送本地保存的黑白本子的
