### ISSUE TITLE
【功能请求】对订阅标签和画师的管理

### ISSUE THREAD

**Issue by bf179** [GardenHamster/Theresa3rd-Bot#33]
目前貌似不能列出所有已订阅的内容，以至于都不是很清楚自己订阅了哪些标签，特别是当标签比较复杂的时候，我还是在控制台里看到标签扫描失败才看得到自己订阅的标签/或者说，大佬的webui什么时候做好啊，或许我们可以先简单做一个list列表出来？
以及，或许是因为pixiv对访问频率的限制？还是因为我加的标签太多了，经常会有订阅的几个标签直接就失败了
贴上一部分log  扫描pixiv标签[小学生,インピオ,Loli,マイクロビキニ,ようじょ,すじ,貧乳,ロリ,JS,萝莉,ペド,幼女,ロリビッチ,JC]订阅失败：获取标签:(小学生 OR インピオ OR Loli OR マイクロビキニ OR ようじょ OR すじ OR 貧 乳 OR ロリ OR JS OR 萝莉 OR ペド OR 幼女 OR ロリビッチ OR JC)作品失败
仅仅是顺便提一下的建议，还是在耐心等待大佬鸽出一个webui的

**Comment by KaRuiqin** [comment]
![spell.png](https://user-images.githubusercontent.com/69111766/228899658-1e73b1a7-cd7d-4ab2-af6c-23f1d983c41d.png)

**Comment by bf179** [comment]
确实很刑

**Comment by GardenHamster** [comment]
- 一般不建议你将这么多个标签连在一起订阅，因为这样的标签P站上也不一定能查的出来
- 订阅内容你可以暂时先查数据库，用Navicat之类的可视化工具可以很方便的查出来

**Comment by GardenHamster** [comment]
而且很多萝莉图实际上都没有打`ロリ`标签，推荐你多订阅几个这个领域的画师

**Comment by bf179** [comment]
确实，也订阅了一些画师，不过很多画师不仅画萝莉，不是很想被推送巨乳之类的图，我都是把巨乳tag加进禁止标签的，不过话说，目前对于搜到的包含禁止标签的图，为什么不是重新获取一次知道不含禁止标签而是直接提示被屏蔽呢
而且直接从tag获取的话会有很多新的图，不仅仅是已关注画师的

**Comment by GardenHamster** [comment]
> 目前对于搜到的包含禁止标签的图，为什么不是重新获取一次知道不含禁止标签而是直接提示被屏蔽呢 而且直接从tag获取的话会有很多新的图，不仅仅是已关注画师的

没理解

**Comment by bf179** [comment]
> > 目前对于搜到的包含禁止标签的图，为什么不是重新获取一次知道不含禁止标签而是直接提示被屏蔽呢 而且直接从tag获取的话会有很多新的图，不仅仅是已关注画师的
> 
> 没理解
![image](https://user-images.githubusercontent.com/65052853/228905015-33ac3ff6-4751-487e-905b-ec8edb0ea52f.png)
我指的是这种情况

**Comment by GardenHamster** [comment]
主要就是不想重复的去请求api，可能有些极端的情况下(屏蔽和很多标签的那种)，有可能会出现一直在发送请求的情况

**Comment by bf179** [comment]
好耶，有订阅列表和画师作品一览了
