### ISSUE TITLE
佬能不能适配go-cqhttp，mirai太容易风控了。

### ISSUE THREAD

**Issue by SkyYeXianer** [GardenHamster/Theresa3rd-Bot#35]
很喜欢使用这款机器人，功能明确不复杂，不会眼花缭乱和各种未知报错。但是mirai我用了好几个小号，而且mirai现在还没有解决方法，每个都是一段时间会就风控报错45了😭😭😭

**Comment by GardenHamster** [comment]
Mirai我自己用起来其实还好，用社区的登陆方案基本都能登上，https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88

**Comment by GardenHamster** [comment]
可能是账号的原因，我只发送缩略图不发送r18，还有图片的代理链接也改了一下，目前我的账号大概已经有半年没有被封过号了吧

**Comment by GardenHamster** [comment]
go-cqhttp我大概是没空去适配了，如果有想法的话欢迎PR

**Comment by GardenHamster** [comment]
在 [v0.10.0](https://github.com/GardenHamster/Theresa3rd-Bot/releases/tag/v0.10.0) 中修改了
