### ISSUE TITLE
『功能建议』添加定时发送随机消息

### ISSUE THREAD

**Issue by Yaosanqi137** [GardenHamster/Theresa3rd-Bot#36]
关于reminder功能，可不可以加一个ramdom选项，由用户设置多条信息，到点机器人随机选一条信息发到群里。

（或者说本身就有这个功能
只是我没在文档上看见）
谢谢大佬！

**Comment by GardenHamster** [comment]
可以，下版本加

**Comment by Yaosanqi137** [comment]
好诶

**Comment by GardenHamster** [comment]
在 [v0.10.0](https://github.com/GardenHamster/Theresa3rd-Bot/releases/tag/v0.10.0) 中修改了
