### ISSUE TITLE
【功能请求】图片发送成功后尝试撤回Bot的响应消息和用户的请求消息

### ISSUE THREAD

**Issue by KaRuiqin** [GardenHamster/Theresa3rd-Bot#37]
![Snipaste_2023-07-19_22-23-11](https://github.com/GardenHamster/Theresa3rd-Bot/assets/69111766/932818ce-8fe6-442e-8ced-8b6dd0de9cc8)

也就是图示的这两条消息，感觉如果群友发多了聊天记录看起来会比较乱 >_<
或者太麻烦的话加入引用用户的请求消息也可以（

**Comment by GardenHamster** [comment]
图里面数字为2的响应消息，其实可以通过清除配置文件中的Template配置达到不发送的效果的

**Comment by GardenHamster** [comment]
引用消息的功能我晚点再加

**Comment by KaRuiqin** [comment]
> 图里面数字为2的响应消息，其实可以通过清空`ProcessingMsg`配置达到不发送的效果的

但是我希望用户知道Bot开始处理他的请求，所以就开了。

**Comment by GardenHamster** [comment]
在 [v0.10.0](https://github.com/GardenHamster/Theresa3rd-Bot/releases/tag/v0.10.0) 中修改了

**Comment by KaRuiqin** [comment]
> 在 [v0.10.0](https://github.com/GardenHamster/Theresa3rd-Bot/releases/tag/v0.10.0) 中修改了

好哦
