### ISSUE TITLE
分开部署机器人和本服务，图片不会正常发送

### ISSUE THREAD

**Issue by xiaoshadan** [GardenHamster/Theresa3rd-Bot#38]
我使用gocq将机器人部署在服务端
在本地运行本服务
发送图片时会出现
[WARNING]: 转换消息 [CQ:image,file=file:///E:/nonebot-use/Theresa3rd-Bot/BotImg/face/error.jpg,type=,subType=0,cache=0] 到MiraiGo Element时出现错误: file not found.
此类错误

**Comment by GardenHamster** [comment]
晚点我用Base64修复一下

**Comment by GardenHamster** [comment]
在 [v0.10.2](https://github.com/GardenHamster/Theresa3rd-Bot/releases/tag/v0.10.2) 中修复了
