### ISSUE TITLE
请问Ubuntu系统应该如何部署呢

### ISSUE THREAD

**Issue by smilecat2788** [GardenHamster/Theresa3rd-Bot#39]
有没有docker部署之类的，教程第一步我就卡住了，Ubuntu好像没有rpm？我百度看centos才能使用rpm，Ubuntu要转换什么的

**Comment by GardenHamster** [comment]
参考下微软的文档
https://learn.microsoft.com/zh-cn/dotnet/core/install/linux-ubuntu

**Comment by smilecat2788** [comment]
安装了.net,也百度了更新证书，启动报错

2023-08-19 10:01:19,794 [1] FATAL [(null)] - 启动异常
(Line: 7, Col: 33, Idx: 873) - (Line: 8, Col: 61, Idx: 952): While parsing a block mapping, did not find expected key.

2023-08-19 10:01:44,628 [1] FATAL [(null)] - 启动异常
(Line: 7, Col: 33, Idx: 873) - (Line: 8, Col: 61, Idx: 952): While parsing a block mapping, did not find expected key.

2023-08-19 10:03:14,532 [1] FATAL [(null)] - 启动异常
(Line: 7, Col: 33, Idx: 873) - (Line: 8, Col: 61, Idx: 952): While parsing a block mapping, did not find expected key.
这是什么原因呢

**Comment by GardenHamster** [comment]
botsettings.yml第7行格式有错误，检查一下

**Comment by smilecat2788** [comment]
root@ubuntu:~# dotnet TheresaBot.MiraiHttpApi.dll --launch-profile Production --urls http://0.0.0.0:9999
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-TheresaBot.MiraiHttpApi.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
  现在变成了这个样子，我百度好像说是没有加入系统变量？

**Comment by smilecat2788** [comment]
General:                                                                            #基础设置
    Prefixs:                    ['&','&']                                          #指令前缀
    DownloadPath:               'BotImg/download'                                   #下载文件的存放目录
    DefaultFontPath:            'Font/simsun.ttc'                                   #默认字体文件路径
    DownPathCleanCron:          '0 0 4 * * ?'                                       #下载目录清理定时器，Cron表达式，空值表示不清理，格式：0 0 4 * * ?
    DownErrorImgPath:           'BotImg/face/error.jpg'                             #图片下载失败时的替代图片
    ErrorGroups:                [480460678]                                                  #错误日志群，发生错误时会将日志发送到这些群
    ErrorMsg:                   |                                                   #处理异常时返回的消息
                                出了点小问题，稍后再试吧
                                [image:BotImg/face/emmm.jpg]
    DisableMsg:                 '该功能未开启'                                      #功能未启用时返回的消息
    NoPermissionsMsg:           '该功能未授权'                                      #功能未授权时返回的消息
    ManagersRequiredMsg:        '该功能需要管理员执行'                              #需要管理员权限时返回的消息
    SetuCustomDisableMsg:       '自定义功能已关闭'                                  #禁用自定义时返回的消息
    SendRelevantCommands:       true                                                #接收到的指令不存在时，提示类似的可执行指令
第7行是错误日志群，这样写符合规则吗，还是说应该加单引号

**Comment by GardenHamster** [comment]
你截图出来吧,这样我根本看不出来

**Comment by smilecat2788** [comment]
<img width="843" alt="image" src="https://github.com/GardenHamster/Theresa3rd-Bot/assets/109615952/fd7e752f-d5f3-496a-8fe7-997b14f55528">

**Comment by GardenHamster** [comment]
你加一下文档里面的QQ群，然后Log目录下面找下日志我看看

**Comment by HuanKongzzz** [comment]
询问一下Ubuntu部署成功了吗

**Comment by GardenHamster** [comment]
> 询问一下Ubuntu部署成功了吗

如果遇到问题发个新的issuse,或者到群里发一下日志
