### ISSUE TITLE
『功能建议』添加Ban画师的功能

### ISSUE THREAD

**Issue by bf179** [GardenHamster/Theresa3rd-Bot#40]
自己尝试了一下，但是这几天qq被风控了登不上测试不了，大致就是类似于HavingBanTags()添加一个IsBanUser()的方法，在push的时候同样判断一下是否是被ban的画师，好像不是很麻烦（？），主要是为了再提升一点推送精度。
  以及，yaml文件太折磨了，对我这种菜鸟来说简直就是魔鬼难度，鬼知道它那里究竟报的什么错（

**Comment by GardenHamster** [comment]
v0.11.0开始可以不用自己改yaml了，可以在WebUI上改

**Comment by GardenHamster** [comment]
鬼畜画师太多了，一个一个的Ban肯定Ban不过来，但是功能还是可以有的

**Comment by bf179** [comment]
> v0.11.0开始可以不用自己改yaml了，可以在WebUI上改

辛苦了，不过目前好像还不能添加画师和标签订阅

**Comment by GardenHamster** [comment]
重构的时候出了点bug没注意，你可以先用带参数订阅那种方式

**Comment by GardenHamster** [comment]
在v0.11.1中添加了
