### ISSUE TITLE
【改进请求】配置文件更新优化

### ISSUE THREAD

**Issue by KaRuiqin** [GardenHamster/Theresa3rd-Bot#42]
目前每次更新的时候还需要手动合并配置文件，这样非常浪费时间与精力。
希望在发布时不带配置文件，如果是第一次运行则生成默认配置文件，则更新的话软件自动合并更新配置文件。

**Comment by bf179** [comment]
每次更新不涉及配置文件的变动的话你应该不需要替换config的，只有release说明了配置文件有变动的话才需要替换config

**Comment by KaRuiqin** [comment]
> 每次更新不涉及配置文件的变动的话你应该不需要替换config的，只有release说明了配置文件有变动的话才需要替换config ![image](https://private-user-images.githubusercontent.com/65052853/291766766-5c4b4607-4d49-4486-8906-0290d9b86cc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDE2MjQsIm5iZiI6MTcwMzA0MTMyNCwicGF0aCI6Ii82NTA1Mjg1My8yOTE3NjY3NjYtNWM0YjQ2MDctNGQ0OS00NDg2LTg5MDYtMDI5MGQ5Yjg2Y2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAzMDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NTNiYWJlYzIxYjU0MmQ0MzU0ZjEyMWQyMGFhYTY2NzMzZGRkN2QyNjA2NThkZGY0NDViNzFkMjZhZmU0YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V3I0mz5aujsmv3py1JqDe19GyrIfr3nTgqE3WrjomZg)

是的，我这里说的就是需要更新配置文件的时候。

**Comment by bf179** [comment]
> > 每次更新不涉及配置文件的变动的话你应该不需要替换config的，只有release说明了配置文件有变动的话才需要替换config ![image](https://private-user-images.githubusercontent.com/65052853/291766766-5c4b4607-4d49-4486-8906-0290d9b86cc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDE2MjQsIm5iZiI6MTcwMzA0MTMyNCwicGF0aCI6Ii82NTA1Mjg1My8yOTE3NjY3NjYtNWM0YjQ2MDctNGQ0OS00NDg2LTg5MDYtMDI5MGQ5Yjg2Y2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAzMDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NTNiYWJlYzIxYjU0MmQ0MzU0ZjEyMWQyMGFhYTY2NzMzZGRkN2QyNjA2NThkZGY0NDViNzFkMjZhZmU0YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V3I0mz5aujsmv3py1JqDe19GyrIfr3nTgqE3WrjomZg)
> 
> 是的，我这里说的就是需要更新配置文件的时候。

那确实（

**Comment by GardenHamster** [comment]
v0.11.0开始增加WebUI以后就不需要替换Config了，添加的新配置项会有个初始值，需要的话在WebUI上修改就行

**Comment by KaRuiqin** [comment]
> v0.11.0开始增加WebUI以后就不需要替换Config了，添加的新配置项会有个初始值，需要的话在WebUI上修改就行

原来是这样
那还是建议发布的时候config文件夹不带有默认配置文件，如果是首次运行的话就让程序生成。
这样的话更新的时候不会替换掉已有的配置，新用户也可以正常使用（

**Comment by bf179** [comment]
> > v0.11.0开始增加WebUI以后就不需要替换Config了，添加的新配置项会有个初始值，需要的话在WebUI上修改就行
> 
> 原来是这样 那还是建议发布的时候config文件夹不带有默认配置文件，如果是首次运行的话就让程序生成。 这样的话更新的时候不会替换掉已有的配置，新用户也可以正常使用（

你的意思是发布的包里不加config文件，这样方便直接把文件解压到目录下不会覆盖原有的yaml文件吗

**Comment by GardenHamster** [comment]
> > v0.11.0开始增加WebUI以后就不需要替换Config了，添加的新配置项会有个初始值，需要的话在WebUI上修改就行
> 
> 原来是这样 那还是建议发布的时候config文件夹不带有默认配置文件，如果是首次运行的话就让程序生成。 这样的话更新的时候不会替换掉已有的配置，新用户也可以正常使用（

就先保持原状吧，后面不会有大改动了
