### ISSUE TITLE
【改进请求】WebUI中的文本编辑框加入右侧滑条

### ISSUE THREAD

**Issue by KaRuiqin** [GardenHamster/Theresa3rd-Bot#43]
当我在WebUI中的文本编辑框编辑过长的消息模板的时候无法通过鼠标滚轮调整浏览的位置，只能使用方向键移动光标。
希望可以在WebUI中的文本编辑框加入侧滑条以更方便的编辑消息模板。

**Comment by GardenHamster** [comment]
这个其实是前端框架的组件问题，以前试过想改但是发现不行，晚点我再给官方发个Issuse看看吧
