### ISSUE TITLE
【功能请求】可以在使用#涩图指令搜索图片时增加推送的图片数量吗

### ISSUE THREAD

**Issue by DarkStrow** [GardenHamster/Theresa3rd-Bot#48]
1）目前只能推送一张，找图片的过程有点像抽卡，希望增加5连抽，10连抽，希望可以增加调数量的功能。
2）希望在pixiv搜图的权重修改上增加点赞量和游览量的权重。

**Comment by GardenHamster** [comment]
因为我还没找到pixiv有哪个api能一次返回多个作品的收藏数和点赞数的，所以也就只能每个作品都调用一次获取详情的api去获取了，这样的话就会导致会向pixiv发送大量的请求，现在采用折中的办法是只要读取到第一张符合要求的作品就停止请求了，所以每次只发送一张也是没有办法的事情
