### ISSUE TITLE
为什么我成功启动后发送命令没有反应？

### ISSUE THREAD

**Issue by SkyYeXianer** [GardenHamster/Theresa3rd-Bot#5]
我已经botsettings.yml修改了群和管理员权限，#涩图却没有反应。连私聊都没有反应。我没有IT基础因此我十分疑惑。
![image](https://user-images.githubusercontent.com/109300803/179026139-34e3c3cd-d6e1-4927-9251-ea9b652fbd59.png)

**Comment by GardenHamster** [comment]
- botsettings.yml修改以后要重启bot，
- 检查一下mcl里面有没有报红，有的说明mcl还没配置好
- 发指令以后检查一下，mcl里面有没有回应，有回应说明账号给风控了
- 如果还是不行，麻烦mcl控制台也截个图，有报错信息的都发一下

**Comment by SkyYeXianer** [comment]
这是我把所有文件卸载后重新按照步骤安装机器人的操作，麻烦大大有空看一下，机器人超酷的好不好😭😭😭[我的操作.docx](https://github.com/GardenHamster/Theresa3rd-Bot/files/9114419/default.docx)

**Comment by SkyYeXianer** [comment]
大大，他有反应了
![image](https://user-images.githubusercontent.com/109300803/179059696-449cc4ab-8190-4883-9c28-110c6afbe554.png)

**Comment by GardenHamster** [comment]
跟着这个配一下cookie
https://github.com/GardenHamster/Theresa3rd-Bot/blob/main/Menu.md

**Comment by SkyYeXianer** [comment]
大大，我有点疑惑botsettings.yml里的DisableTags:['R-18','R18','R18+','R18G']这一项貌似没用，他的效果是什么？
![image](https://user-images.githubusercontent.com/109300803/179164868-da8141e6-d804-4ec5-9807-e00cacec1d36.png)
我测试两个涩图群，一个不给R18权限，一个给R18权限。这个R18权限是不是比DisableTags的权限高啊？有R18权限的群#涩图会出来R18图，没有的就出不来。我理解的是DisableTags禁用的标签不管有没有R18权限都不能搜索，只有解禁才能搜索。如果这个R18权限比DisableTags的权限高按照
![image](https://user-images.githubusercontent.com/109300803/179165664-7c66218c-4b89-4623-aa72-6d3ec5745f83.png)这一句话我的理解，我在没有R18权限的群#涩图 R18+应该会出现‘禁止查找这个类型的涩图’。可是我发现只有在#禁止标签 R18+后才会出现，所以我认为DisableTags:['R-18','R18','R18+','R18G']这一项没有效果。不知道理解的对不对，请大大赐教。

**Comment by GardenHamster** [comment]
DisableTags只是禁止查询的标签，显示或者不显示R18和R18图是在权限里面配置的

**Comment by GardenHamster** [comment]
这块功能晚点我再优化一下

**Comment by SkyYeXianer** [comment]
好的好的
