### ISSUE TITLE
谁是卧底-无法结束游戏

### ISSUE THREAD

**Issue by buggzd** [GardenHamster/Theresa3rd-Bot#54]
# 描述
- 开始游戏后，bot不会私聊发送，在群里发送`#我的词条`后任然没有收到bot的消息，后发现需要添加bot好友才会私发。
![image](https://github.com/GardenHamster/Theresa3rd-Bot/assets/57561662/ec2057d4-54d0-422f-aed5-fcae526126da)
![image](https://github.com/GardenHamster/Theresa3rd-Bot/assets/57561662/67f8b759-a24e-48f6-9a73-9bf75828b344)
- 无法结束游戏，手动输入`#结束游戏`也无法结束游戏，我是拥有管理员权限的
![image](https://github.com/GardenHamster/Theresa3rd-Bot/assets/57561662/61bfe5c7-19fd-4eb2-9fe5-cf4bcb90c02a)
# 版本信息
- LLOneBot：v3.26.4
- Theresa3rd：v0.11.4

**Comment by buggzd** [comment]
# 补充：
## 无法结束游戏触发情况说明
默认4人，开启游戏。
bot未发送词条，所有人都没有收到，包括管理员。
此时发送`结束游戏`无法结束。
再尝试了群呢手动获取词条后，bot给对应有好友位的发送了词条。但是任然无法结束游戏。

## 配置文件
theresa3rdbot:
```
{
  "Mirai": {
    "host": "127.0.0.1",
    "port": "3000",
    "authKey": "theresa3rd",
    "botQQ": "3475555542"
  },
  "GoCqHttp": {
    "host": "127.0.0.1",
    "port": "3001"
  },
  "Database": {
    "ConnectionString": "Data Source=127.0.0.1;port=3306;Initial Catalog=theresa3rdbot;uid=root;pwd=123456#;CharSet=utf8mb4;SslMode=None;AllowPublicKeyRetrieval=True;"
  }
}

```
LLOneBot :
```
{
  "ob11": {
    "httpPort": 3000,
    "httpHosts": [],
    "httpSecret": "",
    "wsPort": 3001,
    "wsHosts": [],
    "enableHttp": true,
    "enableHttpPost": true,
    "enableWs": true,
    "enableWsReverse": false,
    "messagePostFormat": "array",
    "enableHttpHeart": false,
    "enableQOAutoQuote": false
  },
  "heartInterval": 60000,
  "token": "",
  "enableLocalFile2Url": false,
  "debug": false,
  "log": false,
  "reportSelfMessage": false,
  "autoDeleteFile": false,
  "autoDeleteFileSecond": 60,
  "enablePoke": true,
  "musicSignUrl": ""
}
```
## MySql版本
mysql-8.4.0-winx64

## bot后台
bot后台没有看到任何与游戏相关的log，都是米游社和pixiv的订阅更新。

**Comment by GardenHamster** [comment]
到目前LLOneBot v3.26.5版本为止，LLOneBot在向非好友发送临时消息后一直没有消息响应，导致谁是卧底的游戏线程阻塞了，目前原因不明，你可以试试让所有玩家添加bot为好友后在进行游戏，这个问题或许只有等待LLOneBot的后续更新修复了

**Comment by GardenHamster** [comment]
检查了一遍是因为LLOneBot在响应请求的时候没有返回echo导致的，刚发布的LLOneBot v3.26.7已经修复了这个问题

**Comment by GardenHamster** [comment]
另外查了一下LLOneBot本身是不支持发送临时消息的，如果需要接收临时消息还是需要添加Bot为好友

https://llonebot.github.io/zh-CN/develop/api#api-支持情况

![image](https://github.com/GardenHamster/Theresa3rd-Bot/assets/89188316/702afdc1-ae3a-4946-80b5-bce5123e38aa)
