### ISSUE TITLE
为什么机器人只会发送ヾ(≧∇≦*)ゝ，加了好友的

### ISSUE THREAD

**Issue by ELctronicon** [GardenHamster/Theresa3rd-Bot#6]
感觉是mcl出问题了，但不知道怎么解决，求帮帮，大大
![image](https://user-images.githubusercontent.com/109470629/179403419-2d70a507-147a-4c84-b650-9fa747885b8e.png)

**Comment by GardenHamster** [comment]
先检查一下发的指令对不对。还有吧mcl和jdk版本发一下。还有红色的这段报错，全部发出来看看

**Comment by ELctronicon** [comment]
![image](https://user-images.githubusercontent.com/109470629/179406096-318b818c-4b18-44c5-b6a3-8c00d6f6bd92.png)
![image](https://user-images.githubusercontent.com/109470629/179406106-50dcdc11-37ef-49db-8465-5463a48f4806.png)

**Comment by ELctronicon** [comment]
是版本太高了吗(っ °Д °;)っ

**Comment by GardenHamster** [comment]
- 应该跟这个报错无关，毕竟你私聊bot都有回应了。
- ヾ(≧∇≦*)ゝ这个表情是在没有输对指令或者不是好友的情况下才会回复的
- 实在没有头绪可以先换回去jdk11看看

**Comment by ELctronicon** [comment]
上面还有写报错
![image](https://user-images.githubusercontent.com/109470629/179417510-da7982d0-1f88-47d8-9dff-29429c8242d5.png)
输入的指令没问题，可以用指令改cookie，但其他的全是这个表情

**Comment by GardenHamster** [comment]
除了改cookie的指令以外，其他指令都是要发到群里的
