### ISSUE TITLE
运行后依旧无法连接，是否是mcl配置出错？

### ISSUE THREAD

**Issue by KasLee14** [GardenHamster/Theresa3rd-Bot#8]
![QQ截图20220820013640](https://user-images.githubusercontent.com/34614059/185676076-57b71d29-a117-4808-823a-3832794b566f.png)
![image](https://user-images.githubusercontent.com/34614059/185676147-a958e908-821a-489b-a4a6-9159cd3804d1.png)
按照教程配置后迟迟无法连接

**Comment by GardenHamster** [comment]
先检查一下mirai-api-http和配置文件里面的port和verifyKey是否一致
