### ISSUE TITLE
大大，机器人只会发表情

### ISSUE THREAD

**Issue by vansmart521** [GardenHamster/Theresa3rd-Bot#9]
已加机器人好友，私聊机器人也有反应，但是只会发表情。
配置文件中也添加了管理员权限，软件后台有少许报错，我发给你看。
![QQ截图20220822103736](https://user-images.githubusercontent.com/111718628/185827902-d7e415dc-823b-4988-b319-3e24b77587e6.png)
![QQ截图20220822103759](https://user-images.githubusercontent.com/111718628/185827914-9e0c055e-fcaf-4a1b-8394-e83c985255fe.png)
![QQ截图20220822103822](https://user-images.githubusercontent.com/111718628/185827922-e52d5057-5d38-4995-8916-a814847a09a7.png)
聊天记录从第三张图的后台可以看到，不管发什么指令，机器人都是回默认的颜文字。
求大大帮助。

**Comment by vansmart521** [comment]
mcl里没有红色报错，bot里仅有的三段红色报错我都发出来了

**Comment by vansmart521** [comment]
说错了，bot里没有报错，mcl里仅有的三段报错我都发出来了

**Comment by GardenHamster** [comment]
cookie指令才需要私聊，其他指令都要发群里

**Comment by vansmart521** [comment]
#涩图发群里没反应，#涩图和#pivixcookie私聊返回的都是表情

**Comment by GardenHamster** [comment]
那应该会有报错才对，你在log目录下找找看有日志生成吗

**Comment by vansmart521** [comment]
bot里生成了日志，但是都是很平常的东西，没有报错。
mcl里的日志有几行类似于报错的东西。
![QQ截图20220822112718](https://user-images.githubusercontent.com/111718628/185832748-a41b14aa-8784-44f0-9541-74d5a7f2a35d.png)
我感觉既然发消息都有反应，那bot应该是启动了。但是bot里又没有报错，就很奇怪。
这是我这几次的bot日志。
![QQ截图20220822112910](https://user-images.githubusercontent.com/111718628/185832925-ae56b511-aa65-487a-8930-39bcf517c8c8.png)
bot目录下的log里还生成了一个今天日期的空白txt。

**Comment by GardenHamster** [comment]
这种情况多半是权限没配好，又或者是改了配置文件以后没有重启

**Comment by GardenHamster** [comment]
或者你先试试其他指令#version，#瑟图，#菜单这些指令有响应吗，又或者你设置的指令前缀和你现在用的#号并不是同一个

**Comment by vansmart521** [comment]
我直接复制大大的回复，私发回表情，群发没反应。指令前缀怎么看设置的什么，虽然安装过程我并没有修改任何选项，刚刚在bot里也没看到配置前缀的文件。

**Comment by vansmart521** [comment]
看到了，我改一个再试一试

**Comment by vansmart521** [comment]
改完后，重启了还是不行

**Comment by GardenHamster** [comment]
你加个Q群：284196625，然后吧配置文件，聊天记录，mcl还有powershell的都截个图私发给我看看

**Comment by vansmart521** [comment]
感谢

**Comment by GardenHamster** [comment]
群号后两位写反了
